# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - jvoq-eureka-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jvoqcontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6c504c0943a84d409aa354765d1a943b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_53c74527a84c4c0397ce8656162cef0d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jvoqcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c504c0943a84d409aa354765d1a943b }}/servicio-eureka-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'jvoq-eureka-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0d17982290c492da870f3ae8ab5e06e }}
        images: 'jvoqcontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6c504c0943a84d409aa354765d1a943b }}/servicio-eureka-server:${{ github.sha }}'